### PR TITLE
Implemented and integrated QDockWidgets into mainwindow

### PR DESCRIPTION
**Pull request by SpinnerX**
- Refactored tiff/zarr converter to become resizable based on the window sizes.
- Added QDockWidget panel to left and right side that can be also allowed to be attached or detached.
- QDockWindow allows for easier user view of terminal output, and job logs that are also thread-safe.

### CODE REVIEW

**Review by MattHazard — CHANGES_REQUESTED** [review]
Can you remove unnecessary comments like at line 232, "// <----------",  in mainwindow.h for example?

**Comment by SpinnerX** [comment]
Yes, I can.

**Comment by SpinnerX** [comment]
Just made some changes regarding the unnecessary comments.

**Comment by MattHazard** [comment]
Same thing in mainwindow.cpp at line 61, "// <----------------------"

**Comment by SpinnerX** [comment]
Okay, will do that.

**Comment by SpinnerX** [comment]
Just double checked the commit to see if there are any unnecessary comments, and other sort things in the code using the diff, and looks good on my end. Do let me know if I miss anything.

**Review by MattHazard — APPROVED** [review]

**Comment by MattHazard** [comment]
Any follow-up to my other comment? Just writing another comment because I am not sure if you saw it.

**Comment by SpinnerX** [comment]
Yes, those are needed, it seemed that I may have forgotten to commit them along with the other commits. I'll push them right now.

**Comment by SpinnerX** [comment]
Okay, I have just pushed the commit to those two files that you saw in the .pro

**Review by MattHazard — APPROVED** [review]
Testing now

**Pull request closed without merging**
